# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'partsmasterdata/*'

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '553abab0-5db0-4932-aaaf-25147ed09cf7'
  imageRepository: 'partsmasterdata'
  containerRegistry: 'catenaxdevacr.azurecr.io'
  dockerfilePath: 'partsmasterdata/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'catenaxdevacr12483f45-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: './partsmasterdata/pom.xml'
        publishJUnitResults: false
        javaHomeOption: JDKVersion
        jdkVersionOption: '1.11'
        mavenVersionOption: Default
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
