apiVersion: apps/v1
kind: Deployment
metadata:
  name: partsmasterdata
  namespace: partsmasterdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partsmasterdata
  template:
    metadata:
      labels:
        app: partsmasterdata
    spec:
      containers:
      - name: partsmasterdata
        image: catenaxdevacr.azurecr.io/partsmasterdata:100
        env:
          - name: CONTAINERNAME
            value: "poc"
          - name: STORAGE_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                key: sotrage_connectionstring
                name: partsmasterdata-secret
          - name: HTTPUSERNAME
            value: "TractusX"
           - name: HTTPPASSWORD
            valueFrom:
              secretKeyRef:
                key: http_basic_auth_password
                name: partsmasterdata-secret
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: partsmasterdata
  namespace: partsmasterdata
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: partsmasterdata