apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: catenaxdevacr.azurecr.io/portal
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portal-load-balancer
  namespace: portal
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: portal