server:
  port: 8082
scheduler:
  cron: "@daily"
  connector:
    base-url: https://localhost:8081
    login: admin
    password: password
  resources: # resources map contains pairs of: (consumer resourceId) -> (producer URL)
    09da3ef1-cd9e-409e-a8ac-8e8085e8a2dc: https://localhost:8080
logging.level:
  com.tsystems.simplescheduler: DEBUG