server:
  port: 8082
scheduler:
#  cron: "@daily"
  cron: "*/10 * * * * *"
  connector:
    base-url: https://localhost:8081
    login: admin
    password: password
  resources:
    f86c6bb5-a3e7-458e-821d-789b88f441ef: https://localhost:8080