version: '3.4'

services:

  provider:
    build:
      context: ..
      target: prs-connector-provider
      args:
        BUILD_TARGET: prs-connector-provider
    ports:
      - 8181:8181
    volumes:
      - shared-volume:/tmp/copy

  consumer:
    build:
      context: ..
      target: prs-connector-consumer
      args:
        BUILD_TARGET: prs-connector-consumer
    ports:
      - 9191:9191
    volumes:
      - shared-volume:/tmp/copy

  integration-test:
    image: adoptopenjdk:11-jre-hotspot
    command: ci/test.sh
    volumes:
      - shared-volume:/tmp/copy
      - ./ci:/ci


volumes:
  shared-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
