version: '3.4'

services:

  provider:
    build:
      context: .
      target: provider
    ports:
      - 8181:8181
    volumes:
      - shared-volume:/tmp/copy

  consumer:
    build:
      context: .
      target: consumer
    ports:
      - 9191:9191

  integration-test:
    image: adoptopenjdk:11-jre-hotspot
    command: >
      sh -c "curl -O https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
             chmod +x wait-for-it.sh  &&
             ./wait-for-it.sh provider:8181 &&
             ./wait-for-it.sh consumer:9191 &&
             mkdir -p /tmp/copy/source /tmp/copy/dest &&
             echo value-in-test-document > /tmp/copy/source/test-document.txt &&
             curl -X POST 'http://consumer:9191/api/file/test-document?connectorAddress=http://provider:8181/&destination=/tmp/copy/dest/new-document.txt' &&
             sleep 10 &&
             cat /tmp/copy/dest/new-document.txt"
    volumes:
      - shared-volume:/tmp/copy


volumes:
  shared-volume:
