version: '3.4'

services:

  provider1:
    build:
      context: ..
      target: prs-connector-provider
      args:
        BUILD_TARGET: prs-connector-provider
    ports:
      - 8181:8181
    volumes:
      - ./ci/provider1:/tmp/copy/source
      - dst-shared-volume:/tmp/copy/dest

  provider2:
    build:
      context: ..
      target: prs-connector-provider
      args:
        BUILD_TARGET: prs-connector-provider
    ports:
      - 8182:8181
    volumes:
      - ./ci/provider2:/tmp/copy/source
      - dst-shared-volume:/tmp/copy/dest

  provider3:
    build:
      context: ..
      target: prs-connector-provider
      args:
        BUILD_TARGET: prs-connector-provider
    ports:
      - 8183:8181
    volumes:
      - ./ci/provider3:/tmp/copy/source
      - dst-shared-volume:/tmp/copy/dest

  consumer:
    build:
      context: ..
      target: prs-connector-consumer
      args:
        BUILD_TARGET: prs-connector-consumer
    ports:
      - 9191:9191
    volumes:
      - dst-shared-volume:/tmp/copy/dest

  integration-test:
    image: adoptopenjdk:11-jre-hotspot
    command: ci/test.sh
    volumes:
      - dst-shared-volume:/tmp/copy/dest
      - ./ci:/ci

volumes:
  dst-shared-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
