version: '3.4'

services:

  provider:
    build:
      context: .
      target: provider
    ports:
      - 8181:8181

  consumer:
    build:
      context: .
      target: consumer
    ports:
      - 9191:9191
