version: '3.4'

services:

  provider:
    build:
      context: .
      target: provider
    ports:
      - 8181:8181
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8181"]

  consumer:
    build:
      context: .
      target: consumer
    ports:
      - 9191:9191
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9191"]

  integration-test:
    image: adoptopenjdk:11-jre-hotspot
    depends_on:
      - provider
      - consumer
    command: >
      sh -c "sleep 10 &&
             curl -X POST 'http://consumer:9191/api/file/test-document?connectorAddress=http://provider:8181/&destination=/tmp/huhu' &&
             sleep 10 &&
             cat /tmp/huhu"

