apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  accessModes: 
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}