apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  dataspace-connector-mapping
      prefix: /api/v1/dataspace-connector/
      service: https://dataspaceconnector:8080
      timeout_ms: 60000
  name: {{ include "dataspaceconnector.fullname" . }}
  labels:
    {{- include "dataspaceconnector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dataspaceconnector.selectorLabels" . | nindent 4 }}
