# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'connectordns/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from 'connectordns'"