name: CoreServicesBuild

on: 
  push:
    branches: 
    - main
    - feature/CAX-9-onboarding@cicd
    paths:
      - 'coreservices/invitation/src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - uses: azure/docker-login@v1
        with:
          login-server: acrcatenatest.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      - run: |
          docker build -f coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/Dockerfile -t acrcatenatest.azurecr.io/tractusx/core:${{ github.run_id }} .
          docker push acrcatenatest.azurecr.io/tractusx/core:${{ github.run_id }}
            
      # - name: Azure Kubernetes set context
      #   uses: azure/aks-set-context@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     resource-group: catenax-dev-rg
      #     cluster-name: catenax-dev-aks-services
        
      # - name: Create imagepullsecret for Azure Container registry (ACR)
      #   uses: azure/k8s-create-secret@v1.1
      #   with:
      #     namespace: cdns
      #     container-registry-url: catenaxdevacr.azurecr.io
      #     container-registry-username: ${{ secrets.REGISTRY_USERNAME }}            
      #     container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     secret-name: cdns-ips

      # - name: Baking the helm chart to generate the manifests to deploy
      #   uses: Azure/k8s-bake@v1
      #   with:
      #     renderEngine: helm            
      #     helmChart: ./cdnschart/
      #     helm-version: latest
      #     overrides: |
      #       image.tag:${{ github.run_id }}
      #     id: bake
            
      # - name: Deploy app to AKS
      #   uses: azure/k8s-deploy@v1.3
      #   with:
      #     manifests: ${{ steps.bake.outputs.manifestsBundle }}
      #     images: |
      #       catenaxdevacr.azurecr.io/tractusx/cdns:${{ github.run_id }}
      #     imagepullsecrets: |
      #       cdns-ips          
      #     namespace: cdns
      #     route-method: ingress
