# # This is a basic workflow to help you get started with Actions

# name: helm chart connector

<<<<<<< HEAD
# Controls when the workflow will run
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
      branches: 
      - main
    paths:
      - 'connector/**'
=======
# # Controls when the workflow will run
# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#       branches: 
#       - main
#     paths:
#       - 'connector/**'
>>>>>>> 8fd2e2d8d95525f65e962b421958c241ea692cd5
       
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
  
<<<<<<< HEAD
env:
  HELM_EXPERIMENTAL_OCI: 1
  ACR_NAME: catenaxacr.azurecr.io
  version: 0.2.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install helm
      uses: Azure/setup-helm@v1
      with:
            version: 3.5.0
    - name: Clone public tractusx PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v1
      with:
        owner: 'catenax'
        repository: 'tractusx'

    - name: login to acr using helm
      run: |
       echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | helm registry login ${{ env.ACR_NAME }} --username ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin 
    - name: save helm chart to local registry
      run: |
        helm chart save tractusx/connector/infrastructure/dataspaceconnector ${{ env.ACR_NAME }}/helm/connector:${{ env.version }}
      
    - name: publish chart to acr
      run: |
       helm chart push ${{ env.ACR_NAME }}/helm/connector:${{ env.version }}
=======
# env:
#   HELM_EXPERIMENTAL_OCI: 1
#   ACR_NAME: catenaxdev001acr.azurecr.io
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: install helm
#       uses: Azure/setup-helm@v1
#       with:
#             version: 3.5.0
#     - name: Clone public tractusx PUBLIC repository
#       uses: GuillaumeFalourd/clone-github-repo-action@v1
#       with:
#         owner: 'catenax'
#         repository: 'tractusx'

#     - name: login to acr using helm
#       run: |
#        echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | helm registry login ${{ env.ACR_NAME }} --username ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin 
#     - name: save helm chart to local registry
#       run: |
#         helm chart save tractusx/connector/infrastructure/dataspaceconnector ${{ env.ACR_NAME }}/helm/connector:latest
      
#     - name: publish chart to acr
#       run: |
#        helm chart push ${{ env.ACR_NAME }}/helm/connector:latest
>>>>>>> 8fd2e2d8d95525f65e962b421958c241ea692cd5

